#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# auto formatter
# 変更された，もしくは追加された .cs ファイルをフォーマットする
# TODO: cross-platform

FORMATTER='./tool/astyle/mac/bin/AStyle'
OPTIONS='--options=.astylerc --formatted --suffix=none'

for FILE in `git diff --staged --name-only | grep .cs`; do
    ${FORMATTER} ${OPTIONS} ${FILE}
    git add ${FILE}
done
