#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# ステージング済みのファイルを取得
STAGED_FILES=`git diff --staged --name-only | grep .cs`

# エンコードの確認、utf-8じゃないファイルがあればコミットを中止
for FILE in ${STAGED_FILES}; do
    ENCODE=`file -b --mime-encoding ${FILE}`
    if [ ${ENCODE} != 'utf-8' ]; then
        echo "${FILE}のエンコードはutf-8ではありません、utf-8に変換してください"
        exit 1
    fi
done

# auto formatter
# 変更された，もしくは追加された .cs ファイルをフォーマットする
# TODO: cross-platform

FORMATTER='./tool/astyle/mac/bin/AStyle'
OPTIONS='--options=.astylerc'

for FILE in ${STAGED_FILES}; do 
    ${FORMATTER} ${OPTIONS} ${FILE}
done
